services:
  - type: web
    name: attendance-system
    env: python
    region: oregon
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y cmake build-essential
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: true
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
